### ISSUE TITLE
Will not compile in esphome 2021.10.0

### ISSUE THREAD

**Issue by WouterKr** [galagaking/espaxa#3]
Hi,

Hope you can help with this one. Just updated to esphome 2021.10.0 and started the update for the devices.
The ones including espaxa.h will not compile. The first error given is:

```
In file included from src/main.cpp:43:0:
src/espaxa.h: In member function 'virtual void CustomAXA2RemoteUART::loop()':
src/espaxa.h:36:32: error: call of overloaded 'millis()' is ambiguous
     unsigned long now = millis();
                                ^
```
Some more errors are generated and ends with a 'FAILED'
Hope you can solve this and if I can be of any help (sorry not a programmer) please let me know.

Maybe related to : [https://github.com/esphome/esphome/pull/2575](url)

Regards,

Wouter
